baseURL = "https://friendly-raman-43b455.netlify.app/"
languageCode = "en-us"
title = "FunWithData"
#theme="hugo-universal-theme"
theme="Eclectic"

#baseURL = "<Your URL Here>"                    # Hosting location.
#languageCode = "en-us"                         # Locale
#title = "Acme Corporation"                     # Name of the website
#theme = "Eclectic"                             # Name of the theme

[author]                                       # Information about the website author
facebook = "https://facebook.com/example"
twitter = "https://twitter.com/example"
email = "contact@example.org"
name = "Acme Corporation"
location = "New York"
phone = "(999) 999-9999"
hours = "**Mon-Fri:** 9:00AM - 6:00PM, ET"

[menu]                                        # Menu placement

  [[menu.main]]                               #    - Name of the menu
  identifier = "about"                        #       - Identifier
  name = "About"                              #       - Display name (theme specific key)
  url = "/about"                              #       - Target URL
  weight = 1.0                                #       - Sorting order

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 2.0

 [[menu.main]]
  identifier = "privacy"
  name = "privacy"
  url = "/privacy"
  weight = 2.0

[[menu.main]]
  identifier = "terms"
  name = "terms"
  url = "/terms"
  weight = 2.0

[params]                                      # Theme specific parameters
color = "#71B180"
copyright = "Copyright &copy; 2020 FunWithData. All Rights Reserved."
enableEmoji = "true"

  [[params.footer]]
  title = "About"
  content = "FunWithData Site was created to help data enthusiasts understand some elementary procedures for working with data sets used in SAS (Statistical Analysis System)  and Python's corresponding methods. We hope that you will find explanations and examples helpful. Currently, we cover some of the basic techniques for combining tables horizontally and vertically."

  [[params.footer]]
  title = "Recent SAS Blog Posts"
  recents = "blogSAS"
  recentCount = 7.0

  [[params.footer]]
  title = "Recent Pyhon Blog Posts"
  recents = "blogPython"
  recentCount = 7.0

  [[params.footer]]
  title = "Contact Us"
  contact = true